### ISSUE TITLE
Exception: Invalid sigmas. The perplexity is probably too low.

### ISSUE THREAD

**Issue by shoegazerstella** [jiwoongim/ft-SNE#1]
Hello, thanks for this great work!
I was trying to run it with my data (dim (2331, 41376)). However, I get this error:

` kl, Perplexity 100
Iteration: 1.
Perplexities in [nan, nan].
Traceback (most recent call last):
  File "./run.py", line 85, in <module>
    color=color, divtype=divtypet, datatype=datatype)
  File "/src/tsne.py", line 96, in tsne
    find_sigma(X_shared, sigma_shared, N, perplexity, sigma_iters, metric, verbose)
  File "/src/core.py", line 204, in find_sigma
    raise Exception('Invalid sigmas. The perplexity is probably too low.')
Exception: Invalid sigmas. The perplexity is probably too  low. `

I tried to specify an higher perplexity value but didn't work.
I am also sure I don't have NaNs in my data.
Thanks a lot in advance for your help!

**Comment by jiwoongim** [comment]
Please try choosing higher perplexity.
Also, is your data normalized? If not, try normalizing it to [0,1].
